---
<%
  http_port = ENV['KITCHEN_ICINGA2_HTTP_PORT'] || 8080
  https_port = ENV['KITCHEN_ICINGA2_HTTPS_PORT'] || 8443
  db_host = ENV['KITCHEN_DB_HOST'] || '127.0.0.1'
  db_port = ENV['KITCHEN_DB_PORT'] || '3306'
  db_setup_auto = ENV['KITCHEN_DB_SETUP_AUTO'] || 'true'
%>
driver:
  name: vagrant

verifier:
  name: inspec

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.19.36
  attributes:
    icinga2:
      ignore_version: true
    icingaweb2:
      ignore_version: true
      ido:
        <% if db_setup_auto == 'true' %>
        install_mysql_client: false
        <% else %>
        install_mysql_client: true
        <% end %>
        db_host: <%= db_host %>
        db_port: <%= db_port %>
        db_password: X2BM0WKnN
        load_schema: true
    apt:
      compile_time_update: true
      confd:
        install_recommends: false

platforms:
  - name: centos-6.8
  - name: centos-7.2
  - name: ubuntu-14.04
    run_list:
      - recipe[apt::default]
  - name: ubuntu-16.04
    run_list:
      - recipe[apt::default]
  - name: debian-8.5
    run_list:
      - recipe[apt::default]

suites:
  - name: chef12package
    driver:
      require_chef_omnibus: 12.21.4
      network:
        - ["forwarded_port", {guest: 80, host: <%= http_port %>, auto_correct: true}]
        - ["forwarded_port", {guest: 443, host: <%= https_port %>, auto_correct: true}]
    verifier:
      inspec_tests:
        - test/smoke/default/package.rb
    run_list:
      <% if db_setup_auto == 'true' %>
      - recipe[icinga2-test-mysql-instance::default]
      <% end %>
      - recipe[icinga2::default]
      - recipe[icingaweb2::default]
      - recipe[icingaweb2_test::default]
    attributes:
      icingaweb2:
        install_method: package

  - name: chef13package
    driver:
      require_chef_omnibus: 13.3.42
      network:
        - ["forwarded_port", {guest: 80, host: <%= http_port %>, auto_correct: true}]
        - ["forwarded_port", {guest: 443, host: <%= https_port %>, auto_correct: true}]
    verifier:
      inspec_tests:
        - test/smoke/default/package.rb
    run_list:
      <% if db_setup_auto == 'true' %>
      - recipe[icinga2-test-mysql-instance::default]
      <% end %>
      - recipe[icinga2::default]
      - recipe[icingaweb2::default]
      - recipe[icingaweb2_test::default]
    attributes:
      icingaweb2:
        install_method: package

  - name: chef12source
    driver:
      require_chef_omnibus: 12.21.4
      network:
        - ["forwarded_port", {guest: 80, host: <%= http_port %>, auto_correct: true}]
        - ["forwarded_port", {guest: 443, host: <%= https_port %>, auto_correct: true}]
    verifier:
      inspec_tests:
        - test/smoke/default/source.rb
    run_list:
      <% if db_setup_auto == 'true' %>
      - recipe[icinga2-test-mysql-instance::default]
      <% end %>
      - recipe[icinga2::default]
      - recipe[icingaweb2::default]
      - recipe[icingaweb2_test::default]
    attributes:
      icingaweb2:
        install_method: source

  - name: chef13source
    driver:
      require_chef_omnibus: 13.3.42
      network:
        - ["forwarded_port", {guest: 80, host: <%= http_port %>, auto_correct: true}]
        - ["forwarded_port", {guest: 443, host: <%= https_port %>, auto_correct: true}]
    verifier:
      inspec_tests:
        - test/smoke/default/source.rb
    run_list:
      <% if db_setup_auto == 'true' %>
      - recipe[icinga2-test-mysql-instance::default]
      <% end %>
      - recipe[icinga2::default]
      - recipe[icingaweb2::default]
      - recipe[icingaweb2_test::default]
    attributes:
      icingaweb2:
        install_method: source
